// Exercise actual server handlers with deliberately reordered and fragmented streams.
const fs=require('fs'),vm=require('vm'),assert=require('assert'),EventEmitter=require('events');
const root=__dirname+'/',ports={api:3000,map:3001,detection:3002,track:3003,timestamp:3004,timing:3005,iqdata:3006},servers=new Map(),routes=new Map();
const app={use(){},get(p,f){routes.set(p,f);},post(){},listen(){}};function express(){return app;}express.json=express.text=()=>()=>{};
const stash=require('./stash/updates');
const optional=process.argv.includes('--truth'),forwarded=[];
const cfg={network:{ports,tracker_forward:{enabled:optional,host:'tracker',port:9000}},capture:{fc:551000000,device:{gainReduction:[40,40],lnaState:4}},truth:{adsb:{enabled:optional,tar1090:'fixture',delay_tolerance:2,doppler_tolerance:5}},location:{rx:{latitude:1,longitude:2},tx:{latitude:3,longitude:4}}};
const requireMock=n=>({express,net:{Socket:class {connect(p,h,fn){fn();}on(){}write(v){forwarded.push(v);}},createServer(fn){return {listen(p){servers.set(p,fn);}}}},fs:{readFileSync:()=>''},'js-yaml':{load:()=>cfg},dns:{},http:{get(url,options,cb){cb({statusCode:200,on(event,fn){if(event==='data')fn(JSON.stringify({aircraft:[{hex:'abc',lat:1,lon:2,alt_geom:1000,gs:200,track:90}]}));if(event==='end')fn();}});return {on(){},destroy(){}};}},'./bistatic.js':{computeBistaticDelay:()=>1,computeBistaticDoppler:()=>2},'./lib/extrapolation':{},'./lib/retune':{},'./location.js':{hasLocation:()=>optional}}[n]??require(root+n.replace('./','')));
vm.runInNewContext(fs.readFileSync(root+'server.js','utf8'),{require:requireMock,process:{on(){},argv:['node','server.js','config']},console,setTimeout,Date,Promise,Math,Buffer});
function connect(kind){const s=new EventEmitter();s.pauses=0;s.pause=()=>{++s.pauses;};s.resume=()=>{};s.destroy=()=>{throw Error('Unexpected disconnect');};servers.get(ports[kind])(s);return s;}
const sockets=Object.fromEntries(Object.keys(ports).filter(k=>k!=='api').map(k=>[k,connect(k)]));
function send(kind,o){const raw=Buffer.from(typeof o==='string'?o:JSON.stringify(o));for(let i=0;i<raw.length;i+=7)sockets[kind].emit('data',raw.subarray(i,i+7));}
function get(p){let value;routes.get(p)({}, {send(v){value=v;},type(){return this;}});return value;}
(async()=>{
 send('timestamp','1000');send('timing',{timestamp:1000,nCpi:1,cpi:600,uptime:1});send('map',{timestamp:1000,nRows:1,nCols:2,data:[[1,2]],delay:[0,1],doppler:[0]});send('iqdata',{timestamp:1000,frequency:[1],spectrum:[2]});
 const one={timestamp:1000,delay:[1],doppler:[2],snr:[3]},two={timestamp:1500,delay:[4],doppler:[5],snr:[6]};sockets.detection.emit('data',Buffer.from(JSON.stringify(one)+JSON.stringify(two)));await new Promise(setImmediate);
 assert.deepStrictEqual(get('/stash/detection').delay,[1,4]);assert.strictEqual(get('/stash/map').timestamp,1000);assert.deepStrictEqual(get('/stash/timing').nCpi,undefined);assert.deepStrictEqual(get('/stash/iqdata').spectrum,[[2]]);
 if(optional){const last=JSON.parse(get('/api/detection'));assert.deepStrictEqual(last.adsb,[null]);assert.strictEqual(forwarded.length,2);assert(forwarded.every(v=>v.endsWith('\n')));assert.strictEqual(JSON.parse(forwarded[0]).adsb[0].hex,'abc');}else assert.deepStrictEqual(JSON.parse(get('/api/detection')),two);const backlog=Array.from({length:48},(_,i)=>({timestamp:2000+i*500,delay:[i],doppler:[0],snr:[1]}));sockets.detection.emit('data',Buffer.from(backlog.map(JSON.stringify).join('')));await new Promise(setImmediate);assert(sockets.detection.pauses>0);assert.strictEqual(get('/stash/detection').delay.length,50);assert.strictEqual(JSON.parse(get('/api/detection')).timestamp,backlog.at(-1).timestamp);send('detection',{timestamp:30000,delay:[99],doppler:[0],snr:[1]});await new Promise(setImmediate);assert.strictEqual(JSON.parse(get('/api/detection')).delay[0],99);if(optional){assert.strictEqual(forwarded.length,51);assert(forwarded.every(v=>v.endsWith('\n')));}console.log(JSON.stringify({backpressure_no_loss:true,backlog_frames:48,actual_server_reordered_streams:true,coalesced_detection_updates:2,route_compatibility:true,truth_and_tracker_enabled:optional}));
})().catch(e=>{console.error(e);process.exitCode=1;});
